version: '3.8'
services:
  inventory-service:
    image: beerworks/micro-beer-inventory-service
    ports:
      - 8082:8082
    environment:
      SPRING_PROFILES_ACTIVE: digitalocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@13.127.15.134:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":true,"hostName":"13.126.138.255"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"micro-brewery-config"},"failFast":true,"username":"MyUserName","password":"MySecretPassword"}}},"application":{"name":"beer-inventory-service"}}'
      SPRING_ZIPKIN_BASEURL: http://13.232.245.191:9411
  inventory-failover:
    image: beerworks/micro-beer-inventory-failover
    ports:
      - 8083:8083
    environment:
      SPRING_PROFILES_ACTIVE: digitalocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@13.127.15.13:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":true,"hostName":"13.126.138.255"}},"application":{"name":"inventory-failover"}}'
      SPRING_ZIPKIN_BASEURL: http://13.232.245.191:9411
