version: '3.8'
services:
  filebeat:
    image: amitagrawal10/filebeat:7.9.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
    extra_hosts:
      - "elasticsearch:68.183.80.102"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
  inventory-service:
    image: beerworks/micro-beer-inventory-service #Set version if needed, keep in mind 'latest' tag will only be pulled the first time, updates will not automatically get pulled
    ports:
      - 8082:8082
    environment:
      SPRING_PROFILES_ACTIVE: digitalocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@139.59.41.250:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"beer-inventory-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"micro-brewery-config"},"failFast":true,"username":"MyUserName","password":"MySecretPassword"}}},"application":{"name":"beer-inventory-service"}}'
      SPRING_ZIPKIN_BASEURL: http://134.209.154.95:9411
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 2
  inventory-failover:
    image: beerworks/micro-beer-inventory-failover
    ports:
      - 8083:8083
    environment:
      SPRING_PROFILES_ACTIVE: digitalocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@139.59.41.250:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"inventory-failover"}},"application":{"name":"inventory-failover"}}'
      SPRING_ZIPKIN_BASEURL: http://134.209.154.95:9411
    deploy:
      replicas: 2
  beer-service:
    image: beerworks/micro-beer-service
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: digitalocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@139.59.41.250:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"beer-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"micro-brewery-config"},"failFast":true,"username":"MyUserName","password":"MySecretPassword"}}},"application":{"name":"beer-service"}}'
      SPRING_ZIPKIN_BASEURL: http://134.209.154.95:9411
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 2
  order-service:
    image: beerworks/micro-beer-order-service
    ports:
      - 8081:8081
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: digitalocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@139.59.41.250:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"beer-order-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"micro-brewery-config"},"failFast":true,"username":"MyUserName","password":"MySecretPassword"}}},"application":{"name":"beer-order-service"}}'
      SFG_BREWERY_BEER-SERVICE-HOST: http://beer-service:8080
      SPRING_ZIPKIN_BASEURL: http://134.209.154.95:9411
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 2
  gateway:
    image: beerworks/micro-beer-gateway
    ports:
      - 9090:9090
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: digitalocean
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@139.59.41.250:8761/eureka/"},"region":"default","register-with-eureka":false},"instance":{"preferIpAddress":true}}}'
      SPRING_ZIPKIN_BASEURL: http://134.209.154.95:9411
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 2